# fly.toml file generated for ei-ftp on 2022-06-03T11:04:32+02:00

app = "ei-ftp"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  # passive ports matching the first and last of those below, in [services]:
  MAX_PORT = 21005
  MIN_PORT = 21000
  # fix zomble reaping:
  TINI_SUBREAPER = true
  # (optional) uncomment the next line and put your Fly app's IPv4, got from running fly info:
  #ADDRESS = '1.2.3.4'

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  destination = "/data"
  source = "ftp_data"

[[services]]
  internal_port = 21
  protocol = "tcp"

  [[services.ports]]
    port = 21

  [[services.tcp_checks]]
    interval = "5s"
    timeout = "2s"

[[services]]
  internal_port = 21000
  protocol = "tcp"

  [[services.ports]]
    port = 21000

[[services]]
  internal_port = 21001
  protocol = "tcp"

  [[services.ports]]
    port = 21001

[[services]]
  internal_port = 21002
  protocol = "tcp"

  [[services.ports]]
    port = 21002

[[services]]
  internal_port = 21003
  protocol = "tcp"

  [[services.ports]]
    port = 21003

[[services]]
  internal_port = 21004
  protocol = "tcp"

  [[services.ports]]
    port = 21004

[[services]]
  internal_port = 21005
  protocol = "tcp"

  [[services.ports]]
    port = 21005
